[project]
name = "lvenv"
authors = [
    {name = "Bryan Fichera", email="bfichera@anl.gov"},
]
dynamic = ["version"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "lvenv.__version__"}
